# EDA - Exploratory Data Analisys

In [1]:
data_path = '../data/house_data.parquet'
processed_data_path = '../data/house_data_processed.parquet'
import pandas as pd
from pathlib import Path

In [9]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [10]:
df = pd.read_parquet(data_path)
df.head()

,id,total,area,bedroom_qtd,garage,address,state
0,894438651,R$ 860.000,96 m²,2 quartos,2 vagas,"Rua Francisco José da Silva, Morumbi",São Paulo
1,894959499,R$ 2.530.000,182 m²,3 quartos,3 vagas,"Rua Leonardo Cerveira Varandas, Morumbi",São Paulo
2,895093734,R$ 235.000,38 m²,2 quartos,0,"Rua Leandro Teixeira, Morumbi",São Paulo
3,894798128,R$ 298.000,52 m²,2 quartos,1 vaga,"Rua José Dias da Costa, Morumbi",São Paulo
4,894890195,R$ 2.600.000,220 m²,3 quartos,3 vagas,"Rua Adalívia de Toledo, Morumbi",São Paulo

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           996 non-null    str
 1   total        996 non-null    str
 2   area         996 non-null    str
 3   bedroom_qtd  996 non-null    str
 4   garage       996 non-null    str
 5   address      996 non-null    str
 6   state        996 non-null    str
dtypes: str(7)
memory usage: 148.1 KB

In [ ]:
df.describe()

,id,total,area,bedroom_qtd,garage,address,state
count,996,996,996,996,996,996,996
unique,996,421,253,9,9,208,1
top,894438651,R$ 650.000,100 m²,3 quartos,2 vagas,"Rua Antônio Júlio dos Santos, Fazenda Morumbi",São Paulo
freq,1,17,27,376,303,53,996

In [4]:
df.isna().sum().sort_values()

id             0
total          0
area           0
bedroom_qtd    0
garage         0
address        0
state          0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df_processed = pd.read_parquet(processed_data_path)
df_processed.head()

,id,total,area,bedroom_qtd,garage,address,state,district
0,894438651,860000.0,96.0,2,2,Rua Francisco José da Silva,São Paulo,Morumbi
1,894959499,2530000.0,182.0,3,3,Rua Leonardo Cerveira Varandas,São Paulo,Morumbi
2,895093734,235000.0,38.0,2,0,Rua Leandro Teixeira,São Paulo,Morumbi
3,894798128,298000.0,52.0,2,1,Rua José Dias da Costa,São Paulo,Morumbi
4,894890195,2600000.0,220.0,3,3,Rua Adalívia de Toledo,São Paulo,Morumbi

In [7]:
df_processed.info()

<class 'pandas.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           996 non-null    str
 1   total        996 non-null    float64
 2   area         996 non-null    float64
 3   bedroom_qtd  996 non-null    int64
 4   garage       996 non-null    int64
 5   address      996 non-null    str
 6   state        996 non-null    str
 7   district     996 non-null    str
dtypes: float64(2), int64(2), str(4)
memory usage: 117.9 KB